env:
  browser: true
  es6: true

extends:
  - eslint-config-prettier
  - eslint:recommended
  - plugin:@typescript-eslint/recommended

plugins:
  - prettier
  - '@typescript-eslint'

globals:
  Promise: true

rules:
  prettier/prettier:
    - error
  arrow-body-style: off
  no-console: off
  '@typescript-eslint/no-unused-vars': "error"
  '@typescript-eslint/explicit-module-boundary-types': off

parser: '@typescript-eslint/parser'

parserOptions:
  sourceType: module
